services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb_connect
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
    networks:
      - questdb
    volumes:
      - ./.questdb_data:/root/.questdb/db

  questdb-connect:
    container_name: questdb_connect_tests
    build: .
    environment:
      QUESTDB_CONNECT_HOST: "questdb"
    depends_on:
      - questdb
    networks:
      - questdb

networks:
  questdb: